### ISSUE TITLE
React Chooser onDeleteAccount event does not return accountId as specified in the docs

### ISSUE THREAD

**Issue by Avadakedvr** [Kloudless/file-picker#125]
Hi there,

I'm currently using the Kloudless's React **Chooser** component to let the user connect to multiple providers and import files from any of those. Based on the accounts that the user is connected to, I'd like to implement search functionality outside of the Chooser component using the Kloudless API. To implement Search, I need to know all the account Ids that the user has connected to within a specific browser. The React component saves this information within the local storage by default, but I have no access to that since it is under Kloudless domain.

I've figured a workaround for this - use the events available to know when a user connects/disconnects from an account and track that by updating this information within the local storage myself - which I can access later and see which accounts the user has connected to. The problem is that the **deleteAccount(accountId)** event as specified here: https://github.com/kloudless/file-picker#events does not actually return the accountId. The **addAccount(account)** returns an object which includes the id of the account that was just added/connected but the **deleteAccount(accountId)** does not return the accountId as shown in the docs (it only gives me an empty object) - and this is a problem since I need to know when an account is removed (the accountId of that) so that I can update my version of the localStorage. 

Please fix that of give me some other solution for this if there exists one! Thanks!

**Comment by fsworld009** [comment]
Hi @Avadakedvr, we are currently making a fix for the deleteAccount event to return accountId. I'll update you once this is released.

**Comment by Avadakedvr** [comment]
> Hi @Avadakedvr, we are currently making a fix for the deleteAccount event to return accountId. I'll update you once this is released.

great ! Waiting for that since I can't continue with my implementation without it working! Thanks!

**Comment by ueewbd** [comment]
Hi @Avadakedvr ,

We've released v2.6.4 to include account ID in the deleteAccount event.
Sorry for the inconvenience.
