### ISSUE TITLE
Display error message when OAuth access_denied occurs

### ISSUE THREAD

**Issue by vinodc** [Kloudless/file-picker#4]
The pop-up window just closes on an error in authentication right now. It would be better to display an error message in addition to this.

**Comment by vinodc** [comment]
The OAuth flow displays an error message now.

**Comment by JackWCollins** [comment]
Hi @vinodc, we are seeing this error on our end, and I believe it is happening in the file picker during the authentication step. When we do the code exchange on the server to `v1/oauth/token` after authentication, we just get back an error from Kloudless that says `access_denied`. I didn't see this on the [Error Code Table](https://developers.kloudless.com/docs/latest/core#error-handling-error-code-table) so I'm not sure why this is occurring. Is this the access_denied from the user, as in they didn't enter the correct credentials? Or perhaps their organization settings didn't allow access?

Thanks!

**Comment by vinodc** [comment]
Hi @JackWCollins. That error is part of the OAuth spec and usually indicates that the user has either denied granting access, or the third-party service has denied the user the ability to grant access to the level requested.
