### ISSUE TITLE
Saver/Chooser window isn’t responsive - Can’t tap “Save” on iOS

### ISSUE THREAD

**Issue by alexweinstein** [Kloudless/file-picker#56]
On iOS, I can't scroll to see the full content, so the Save button isn't tappable. Here is a screenshot from your [JSBin](https://output.jsbin.com/wilowep/) example.
![screenshot](https://cl.ly/193F1y3y1f3w/[d167a9c35e202b94361afce333ab75e2]_IMG_3653.PNG)

**Comment by vinodc** [comment]
@alexweinstein Thanks for letting us know. We've confirmed this issue on iOS.

**Comment by ueewbd** [comment]
Fixed with v2.
