### ISSUE TITLE
Chrome console showing an error 404

### ISSUE THREAD

**Issue by frumbert** [Kloudless/file-picker#63]
Just trying out with my developer account in which I',m using chooser and saver.

About a second or so after my app loads, this shows up on the chrome console:

    [Tue Nov 21 2017 22:41:50 GMT+1100 (AEDT)] body 404 Not Found get /p/platform/explorer/explorer.html?app_id=(hidden)&exp_id=535840947302&flavor=chooser&origin=https%3A%2F%2F(hidden)&custom_css=false&multiselect=false&link=true&computer=false&copy_to_upload_location=false&upload_location_uri=&services=null&persist=%22local%22&account_key=false&create_folder=true&types=[] 

When I press a button to start a chooser, I'm setting up a reference to the explorer, then using the success event to grab the value.

    var KLOUDLESS_APP_ID = (hidden), 
    		KLOUDLESS_INSTANCE = window.Kloudless.explorer({
			"app_id": KLOUDLESS_APP_ID,
			"flavor": "chooser",
			"retrieve_token": true
		})

 That actually all works, but as soon as the explorer window appears I also see a similar console message  - 404 not found , etc

**Comment by vinodc** [comment]
Hi @frumbert We are aware of this issue and are taking steps to resolve it in a refactored release in the upcoming weeks. However, you should not notice any impact on your application. It is due to an internal routing failure in the JS application logic.

**Comment by frumbert** [comment]
Nice, thanks

**Comment by sebastianbk** [comment]
@vinodc I am still experiencing this issue. Do you have a way to solve it?

**Comment by vinodc** [comment]
Hi @sebastianbk. I've confirmed the issue has re-appeared and have re-opened this ticket as well as created one to track it internally. While I don't have a timeline on a solution, we'll be sure to post any updates here after we have an opportunity to investigate the cause. The 404 is informational regarding internal routing and should not impact functionality. If you require a faster resolution, you can also build the file explorer from source to investigate which route could be the concern.

**Comment by vinodc** [comment]
This was resolved at some point the past few years, so this ticket can now be closed.
