### ISSUE TITLE
Breadcrumbs are not aligned when width is constrained in Safari

### ISSUE THREAD

**Issue by vinodc** [Kloudless/file-picker#65]
The attached screenshot shows a misalignment in breadcrumbs:

<img width="622" alt="screen shot 2018-04-17 at 12 08 35 pm" src="https://user-images.githubusercontent.com/616742/38858598-018df91a-41e1-11e8-8115-d676bb09be7c.png">

**Comment by ueewbd** [comment]
We've fixed this in the release of File Picker v2.
Close.
