### ISSUE TITLE
Explorer default to My Computer

### ISSUE THREAD

**Issue by chriskinsman** [Kloudless/file-picker#68]
I only want folks to upload from their computer.  I have tried 

services: ['my computer']

But that still makes them pick the only item there just to upload.  Is there a way to bypass that?

**Comment by chri-roch12** [comment]
Thanks for pointing this out. I'll check in with our team and see if it is possible when only the `computer: true` is used and no services are listed, they are moved directly to selecting the destination rather than having to selec 'My Computer'.

**Comment by vinodc** [comment]
@chriskinsman At the moment there isn't a way to directly open to the Computer view. However you could use the "Dropzone" mode (https://github.com/Kloudless/file-explorer#dropzone-1) to have the user's first interaction be with the Computer option.

**Comment by vinodc** [comment]
This is now possible with the combination:
```
  computer: true,
  account_management: false,
  services: [],
```
