### ISSUE TITLE
Cancel cancel causes upload

### ISSUE THREAD

**Issue by jklingen92** [Kloudless/file-picker#71]
If this is the wrong place to report this issue, please let me know and I will move it elsewhere.

We observed the following behavior in the Kloudless File Explorer:

![image](https://user-images.githubusercontent.com/8923518/55092163-77f79780-5088-11e9-8b57-71ad70c7c3f1.png)

- We choose the local file explorer:
![image](https://user-images.githubusercontent.com/8923518/55092276-a83f3600-5088-11e9-8fcf-174327405ed2.png)

- We add a local file. The file is displayed at 0% upload progress:
![image](https://user-images.githubusercontent.com/8923518/55092300-b8571580-5088-11e9-9e49-1bbc3e0e4c4e.png)

- We hit cancel. A confirmation dialog appears:
![KloudlessUploaderCancel](https://user-images.githubusercontent.com/8923518/55092318-c73dc800-5088-11e9-89a1-520b1c1e4b55.png)

- We cancel the cancel through the confirmation dialog. This incorrectly triggers the upload:
![KloudlessUploaderCancel2](https://user-images.githubusercontent.com/8923518/55092871-be012b00-5089-11e9-9565-ab2d7b148135.png)
**Note that the `Upload` button doesn't change to `Pause` and the `Cancel` button is highlighted**

- We then remain on this screen until the upload button is clicked.
![image](https://user-images.githubusercontent.com/8923518/55092386-e5a3c380-5088-11e9-92bf-b34de5fccbf7.png)

**Comment by vinodc** [comment]
Thanks! It appears that cancelling the cancellation resumes the upload without checking to see if the upload was started in the first place. We'll look into fixing this. Do you mind sending an email with this GitHub URL and your Kloudless developer account email or application ID to support@kloudless.com so we can prioritize this internally?

**Comment by ueewbd** [comment]
We've fixed this in the release of File Picker v2.
Close this issue.
