### ISSUE TITLE
Using `multiselect: false` still shows multiple file selection dialog

### ISSUE THREAD

**Issue by aaronbeall** [Kloudless/file-picker#91]
With `multiselect: false` I noticed that the browser file dialog (when uploading from My Computer) still allows the selection of multiple files (even though the Explorer ends up only using the first one). AFAIK this is because the `<input>` still has the `multiple` attribute:

![image](https://user-images.githubusercontent.com/2973900/68421617-9b310c00-016c-11ea-8b3f-4e19a7631e7d.png)

I would think that `multiselect: false` should omit the `multiple` attribute.

**Comment by pseudonumos** [comment]
thanks @aaronbeall! we'll look into why this is occurring, and we'll keep you updated on the status of this issue.

**Comment by aaronbeall** [comment]
A related problem with `multiselect: false` is that after you've selected a file, you can't select another without manually removing the previous one -- even though it lets you click "Add Files" and choose a file, it doesn't end up in the selection list. 

Another small thing, the "Add Files" should say "Add File" or simply "Select File".

**Comment by vinodc** [comment]
Thanks again for the suggestion! Our latest design disables `Add Files` once a single file is selected, although it still says "Files" initially for easier i18n purposes.
