### ISSUE TITLE
Dropzone allows dropping wrong file types

### ISSUE THREAD

**Issue by aaronbeall** [Kloudless/file-picker#94]
It seems the `dropzone()` component will allow the user to drop any kind of file, disregarding the `types` option. Ideally it would display some kind of feedback when dragging over, showing positive for allowed files and negative for disallowed files.

**Comment by ueewbd** [comment]
Hi aaronbeall,

Thanks for reporting this bug, we're taking steps to fix this.

**Comment by ueewbd** [comment]
Hi @aaronbeall ,

Actually, File Picker will show an error message at the bottom when users drag in files that are wrong type.
Does that work for you? Or you want to prevent users from dragging in wrong type files?

<img width="643" alt="Screen Shot 2020-01-31 at 4 38 05 PM" src="https://user-images.githubusercontent.com/8930307/73524569-5acdeb00-4448-11ea-815e-c5bcbab3a7bb.png">

**Comment by aaronbeall** [comment]
Yeah, I was not seeing that. I will try updating to the latest and double-check.

**Comment by vinodc** [comment]
We'll resolve this ticket since the new UI handles this scenario.
